# .readthedocs.yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    
# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Use Python 3.8 to build the documentation
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

# Formats to be built
formats:
  - pdf
  - epub
